// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABB0YHs-KSUE7_t047WFkQ8v9GRe3LQjs',
    appId: '1:348302294570:android:b8e5b42b56014d34044d53',
    messagingSenderId: '348302294570',
    projectId: 'nemurigi-kobo',
    databaseURL: 'https://nemurigi-kobo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemurigi-kobo.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7T59uTvZ3adaFqOsVO5iw8WbfqDxzIo',
    appId: '1:348302294570:web:dc3a29637b11e2fa044d53',
    messagingSenderId: '348302294570',
    projectId: 'nemurigi-kobo',
    authDomain: 'nemurigi-kobo.firebaseapp.com',
    databaseURL: 'https://nemurigi-kobo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemurigi-kobo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADHpeZKQlPv_i1BnzX6W0kdz851sdwV4s',
    appId: '1:348302294570:ios:484ebda2f76caf23044d53',
    messagingSenderId: '348302294570',
    projectId: 'nemurigi-kobo',
    databaseURL: 'https://nemurigi-kobo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemurigi-kobo.firebasestorage.app',
    iosBundleId: 'com.example.kMaps',
  );

}